#---------------------------------------------------------------
#--------------------  DATABASE - JPA  -------------------------
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: <url to database>
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  #--------------------------------------------------------------
  #--------------------------   REDIS   -------------------------
  data:
    redis:
      host: <host>
      port: <port>

#---------------------------------------------------------------
#--------------------------  DOMAIN  ---------------------------
domain:
  backend: <domain to frontend>
  frontend: <domain to backend>

#---------------------------------------------------------------
#--------------------------  SERVER  ---------------------------
server:
  port: <port>